### ISSUE TITLE
Update the docker hub image description

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [GitTools/build-images#3]
The description of the [gittools/gitversion docker image on docker hub](https://hub.docker.com/r/gittools/gitversion) currently shows to use the `5.3.5-linux-alpine.3.10-x64-netcoreapp3.1` tag. It's reasonable that this version doesn't change very often because it's a hassle to manually update this everytime there's a new version, but can we update this once now?

The reason for this is that version 5.3.5 doesn't recognise the `main` branch as a main branch, only `master`, and `develop`.

If we can bump this version to 5.6.11 that would save people who copy paste from docker hub.

Can we also add a windows friendly command version as well?

```
docker run --rm -v "%CD%:/repo" gittools/gitversion:5.6.11-debian.10-x64 /repo
```

**Comment by asbjornu** [comment]
Thanks for the nudge, I updated to `gittools/gitversion:5.6.10-alpine.3.12-x64-3.1` now. This is going to slip again in the future, though, since it's a manual operation. The optimal thing would be to have a GitHub Action running `on: release` [updated the README on Docker Hub automatically](https://gist.github.com/chrodriguez/f4f4fb9c42d429e3b9a22151cecd178a).

I've created GitTools/GitVersion#2742 to track this improvement.
